name: CI

on:
  push:
    branches: [ Fusión-frontend-y-backend ]
  pull_request:
    branches: [ Fusión-frontend-y-backend ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v3

      - name: Instalar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Instalar dependencias
        run: npm install

      - name: Ejecutar tests
        run: npm test
